require "piggybak_free_shipping_by_product/engine"
require "piggybak_free_shipping_by_product/free_shipping_by_product"
require "piggybak_free_shipping_by_product/piggybak_orders_controller_decorator"

module PiggybakFreeShippingByProduct
end
